site:
  title: Adoption Blueprints Lab
  url: https://rdiazgav.github.io
  start_page: adoption-blueprints-lab::index.adoc

content:
  sources:
    - url: .
      start_path: docs

ui:
  bundle:
    url: ./docs/ui/ui-bundle.zip

output:
  dir: docs-site
