site:
  title: Adoption Blueprints Lab
  url: https://rdiazgav.github.io/adoption-blueprints-lab
  start_page: adoption-blueprints-lab::index.adoc

content:
  sources:
    - url: .
      start_path: docs

ui:
  bundle:
    url: https://github.com/antora/antora-ui-default/releases/download/latest/ui-bundle.zip
    snapshot: true

output:
  dir: docs-site
