apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-istio-system.yaml
  - namespace-istio-cni.yaml
  - namespace-istio-ingress.yaml
  - istio-cni.yaml
  - istio.yaml
  - kiali.yaml
  - ossmconsole.yaml
  - gateway-infra.yaml
