apiVersion: v1
kind: Service
metadata:
  name: postgresql-orders
  namespace: retailflow
  labels:
    app.kubernetes.io/name: postgresql-orders
    app.kubernetes.io/part-of: retailflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgresql-orders
    app.kubernetes.io/part-of: retailflow
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
