apiVersion: v1
kind: Service
metadata:
  name: recommendations
  namespace: retailflow
  labels:
    app.kubernetes.io/name: recommendations
    app.kubernetes.io/part-of: retailflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: recommendations
    app.kubernetes.io/part-of: retailflow
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
