apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: retailflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders
  namespace: retailflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
  namespace: retailflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: retailflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendations
  namespace: retailflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: retailflow
