apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - peer-authentication.yaml
  - payments-destination-rule.yaml
  - payments-virtual-service.yaml
  - catalog-destination-rule.yaml
  - catalog-virtual-service.yaml
  - frontend-peer-authentication.yaml
