apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: retailflow
spec:
  mtls:
    mode: STRICT
  portLevelMtls:
    5432:
      mode: DISABLE
    6379:
      mode: DISABLE
