apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-payments
spec:
  template:
    spec:
      volumes:
        - name: data
          emptyDir: null
          persistentVolumeClaim:
            claimName: postgresql-payments-pvc
