apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-source-pvc
  namespace: retailflow
  labels:
    app.kubernetes.io/part-of: retailflow
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
